name: 02 - workflow events
on: push

jobs:
    echo:
        runs-on: ubuntu-latest
        steps:
            - name: Trigger Message
              run: echo "triggered by event ${{ github.event_name }}"