name: event and activity types
on:
    pull_request: 
        types: 
            - opened
            - synchronize
        branches: 
            - main 

jobs:
    echo:
        runs-on: ubuntu-latest
        steps:
            - run: "trigger when a pr is raised or updated on main"