name: usning expressions

on:
    push: 
    workflow_dispatch: 
        inputs:
            debug:
                type: boolean
                default: false

jobs:
    echo:
        runs-on: ubuntu-latest
        steps:
            - name: '[debug] print any time'
              if: inputs.debug
              run: |
                echo "Triggred By: ${{ github.event_name }}"
                echo "Runner OS: ${{ runner.os }}"

            - name: '[debug] print when triggred by main'
              if: inputs.debug && github.ref == 'refs/heads/main'
              run: echo "TRIGGRED BY MAIN"
              